"""Vars table.

Revision ID: 5c3551b7f40f
Revises: ab8f9cceb464
Create Date: 2023-05-16 06:28:23.953861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3551b7f40f'
down_revision = 'ab8f9cceb464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecast_vars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tm_arr', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_forecast_vars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_forecast_vars_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_forecast_vars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_forecast_vars_id'))

    op.drop_table('weather_forecast_vars')
    # ### end Alembic commands ###
